version: '2'
services:
  node1:
    image: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1,node2
    restart: unless-stopped

  node2:
    image: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: demo
      CASSANDRA_SEEDS: node1,node2
    restart: unless-stopped

  app:
    image: books-api
    ports:
      - "8080:8080"
    restart: unless-stopped