version: '2'
services:
  node1:
    image: books-cassandra
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    restart: unless-stopped

  node2:
    image: books-cassandra
    environment:
      CASSANDRA_SEEDS: node1
    restart: unless-stopped

  app:
    image: books-api
    ports:
      - "8080:8080"
    restart: unless-stopped